# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d2c11fba73dd5f0c137f905d6443cf4acc8664c20a6ccb34b6e0a4524ee85d3f86ed63f4731fbfa7047dcde1e69124710258f8989962fa442ba087cc33c8e83

test:
  secret_key_base: a7f663c68085e8ae44a9af5cb71cbcb747f9d28a742d49507e2b9153e0ffc677277f07450db915973c65bd10c471edf4e02569cfb1c089b041375949ba7d116d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
